version: '3.8'

services:
  postgres:
      image: postgres:latest
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: postgres
        PGDATA: /data/postgres
      # volumes:
      # - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql  
      restart: unless-stopped  
      ports:
        - "5432:5432"